# description
name: "qwerty"
description: ""
keywords: "css, javascript, art"
author: "Leszek Pietrzak"

# address settings
baseurl: "http://qwerty.smutnyleszek.com"
rootSiteUrl: "http://smutnyleszek.com"

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
    auto_ids: false
timezone: Europe/Warsaw

# excludes
exclude:
    - LICENSE
    - README.md
