# description
name: "qwerty"
description: "Hello, World!"
keywords: "css, javascript, art"
author: "Leszek Pietrzak"

# address settings
baseurl: "http://qwerty.magicznyleszek.xyz"
rootSiteUrl: "http://magicznyleszek.xyz"

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
    auto_ids: false
timezone: Europe/Warsaw
port: 2038

# excludes
exclude:
    - LICENSE
    - README.md
